/**
 * Pulls the signed verification token out of the backend authorise response.
 *
 * For integrations that perform server-side payment verification (e.g. e-commerce
 * plugins such as WooCommerce), the verification token is generated by the Monek
 * backend and is treated as an opaque value by the SDK. The SDK simply transports
 * the token to the integration's server-side verification endpoint, where it can
 * be validated before the payment is considered verified.
 *
 * This mechanism is intended for server-side verification flows only and is not
 * required for embedded integrations, which rely on the payment result returned
 * directly by the gateway.
 *
 * Multiple response field names are checked to ensure compatibility across
 * backend contract variations.
 */
export function extractVerificationToken(response: unknown): string | undefined {
    if (!response || typeof response !== "object") {
        return undefined;
    }

    const record = response as Record<string, unknown>;
    const nested = record.verification as Record<string, unknown> | undefined;

    const candidates: unknown[] = [
        record.verification,
        record.verificationToken,
        record.signedToken,
        record.signature,
        nested && typeof nested === "object" ? nested.token : undefined,
    ];

    for (const candidate of candidates) {
        if (typeof candidate === "string" && candidate.length > 0) {
            return candidate;
        }
    }

    return undefined;
}
