name: Deploy SDK to Production

on:
  workflow_dispatch:

env:
  AWS_REGION: eu-west-2
  NODE_VERSION: 22.x
  PIPELINE_EXECUTION_ROLE: arn:aws:iam::265496604514:role/GitHub-Actions-Workflow
  SDK_BUCKET: checkout-js.monek.com

jobs:
  Build-SDK:
    runs-on: ubuntu-latest
    needs: Deploy-Stack
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: EmbeddedCheckout/src/SDK/package-lock.json
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            audience: sts.amazonaws.com
            aws-region: ${{ env.AWS_REGION }}
            role-to-assume: ${{ env.PIPELINE_EXECUTION_ROLE }}
            role-session-name: feature-deployment
            role-duration-seconds: 3600
            role-skip-session-tagging: true

      - name: Install dependencies
        continue-on-error: true
        working-directory: EmbeddedCheckout/src/SDK
        run: npm install
          
      - name: Build
        working-directory: EmbeddedCheckout/src/SDK
        run: npm run build
          
      - name: Deploy
        run: aws s3 sync ./EmbeddedCheckout/src/SDK/dist s3://${{ env.SDK_BUCKET }} --delete